### ISSUE TITLE
stable tag of docker image does not work as per documentation

### ISSUE THREAD

**Issue by nbraun-wolf** [xcnt/kubernetes-update-manager#4]
Hi, I have tried to use today the update manager.  I did not manage to get the [stable ](https://hub.docker.com/layers/xcnt/kubernetes-update-manager/stable/images/sha256-b372481d0605e9bd1b9c7ce237c3046264fa2e7bc23ba6bec6b6e1e46d556d30?context=explore) tag working as per documentation.

First I tried the provided example (configured with the appropriate URL etc.  using defaults from example for simplicity below). But it told me the `--url` flag is not defined.

```bash
$ docker run --rm -t xcnt/kubernetes-update-manager:stable \
    --url https://up.xcnt.io/updates \
    --image xcnt/kubernetes-update-manager:1.0.0 \
    --update-classifier stable
Incorrect Usage. flag provided but not defined: -url

NAME:
   cqrs-dgpr-server - A new cli application

USAGE:
   cqrs-dgpr-server [global options] command [command options] [arguments...]

VERSION:
   stable-$(date +%Y%m%d%H%m%S)

DESCRIPTION:
   GDPR compatible encryption and decryption of events with included key management

AUTHOR:
   XCNT GmbH

COMMANDS:
   server   
   backup   
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
flag provided but not defined: -url
```

Next I have tried to add the `update` command, as It can bee seen in the gif and also in the[ source code](https://github.com/xcnt/kubernetes-update-manager/blob/develop/cli/updateCommand.go). 

![Update Example](https://raw.githubusercontent.com/xcnt/kubernetes-update-manager/develop/images/update-command.gif)

```bash
$ docker run --rm -t xcnt/kubernetes-update-manager:stable update \
    --url https://my-update-manager.sample/updates \
    --image traefik/whoami:v1.6.1 \
    --update-classifier sample \
    --api-key supersecretkey
No help topic for 'update'
```

Eventually, I have tried with [version 1.0.1](https://hub.docker.com/layers/xcnt/kubernetes-update-manager/1.0.1/images/sha256-873fe3708ed929142f3d4b4ca3a457f33860e77f2caa9a109fa14514fe77949b?context=explore). This worked as expected.

```bash
$ docker run --rm -t xcnt/kubernetes-update-manager:1.0.1 update \
    --url https://my-update-manager.sample/updates \
    --image traefik/whoami:v1.6.1 \
    --update-classifier sample \
    --api-key supersecretkey
Updating https://my-update-manager.sample/updates with image traefik/whoami:v1.6.1 and update classifier sample
  --- 1 deployments:  [====================================================================] 100%
Finished
```

**Comment by cbrand** [comment]
Hey thank you for reporting this. That was definitely a miss-configuration on our side and should be fixed now. Sorry for the inconvenience.
